steps:
  - group: ":test_tube: Test"
    key: "test"
    steps:
    - label: ":lab_coat: Unit Tests"
      command: "earthly +test"
      plugins:
        - test-collector#v1.0.0:
            files: "junit-results.xml"
            format: "junit"
    - label: ":goggles: Code Coverage"
      command: "earthly +coverage"
      plugins:
        - joscha/codecov#v3.1.0:
            pgp_public_key_url: "https://keybase.io/codecovsecurity/pgp_keys.asc"
            args:
              - "-s $BUILDKITE_BUILD_CHECKOUT_PATH"
  - group: ":hammer: Build"
    key: "build"
    steps:
      - label: ":hammer: Building"
        command: "earthly +build"
