steps:
  - group: ":test_tube: Test"
    key: "test"
    steps:
    - label: ":test_tube: Testing"
      command: "earthly +test"
      plugins:
        - test-collector#v1.0.0:
            files: "junit-results.xml"
            format: "junit"
            api-token-env-name: "UNREAL_CI_TEST_TOKEN"
  - group: ":hammer: Build"
    key: "build"
    steps:
      - label: ":hammer: Building"
        command: "earthly +build"
